version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/config:/mosquitto/config/:rw
      - ./mosquitto/log/:/mosquitto/log/


