version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/config:/mosquitto/config/:rw
      - ./mosquitto/log/:/mosquitto/log/
  app:
    build: ./app
    depends_on:
      mosquitto:
        condition: service_started
    network_mode: "host"
    volumes:
        - ./app:/app
  server:
    build: ./server
    depends_on:
      mosquitto:
        condition: service_started
    volumes:
        - ./server:/server
    ports:
      - 8000:5000

